# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_markdown.models.MarkdownField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
