# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 01:51
from __future__ import unicode_literals

import datetime
from django.db import migrations
from django.utils.timezone import utc
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20160302_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='apresentation',
            field=django_markdown.models.MarkdownField(default=datetime.datetime(2016, 3, 3, 1, 51, 59, 791965, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
