# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 02:11
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160303_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='description',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
