# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20160303_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', django_markdown.models.MarkdownField(blank=True)),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('description', django_markdown.models.MarkdownField(blank=True)),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='about',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
