# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20160303_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
    ]
