# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-03 14:36
from __future__ import unicode_literals

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_work_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='apresentation',
            field=django_markdown.models.MarkdownField(blank=True),
        ),
    ]
